apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devsecops
data:
  DB_HOST: "10.12.0.3"
  DB_NAME: "appdb"
  USER_SERVICE_URL: "http://user-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  ORDER_SERVICE_URL: "http://order-service:3003"